# Generated by Django 4.1.5 on 2023-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="addpur",
            fields=[
                (
                    "APID",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="加購產品編號",
                    ),
                ),
                (
                    "APNAME",
                    models.CharField(default="", max_length=15, verbose_name="加購產品名稱"),
                ),
                (
                    "APSIZE",
                    models.CharField(default="", max_length=10, verbose_name="尺寸"),
                ),
                (
                    "APCOLOR",
                    models.CharField(default="", max_length=10, verbose_name="顏色"),
                ),
                ("APPRICE", models.IntegerField(default="", verbose_name="價格")),
            ],
        ),
        migrations.CreateModel(
            name="bag",
            fields=[
                (
                    "BID",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="洗衣袋編號",
                    ),
                ),
                (
                    "STATE",
                    models.CharField(default="", max_length=10, verbose_name="狀態"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="delivery",
            fields=[
                (
                    "ORDID",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="訂單編號",
                    ),
                ),
                (
                    "SHOPID",
                    models.CharField(default="", max_length=10, verbose_name="店鋪編號"),
                ),
                (
                    "PHONE",
                    models.CharField(default="", max_length=15, verbose_name="使用者電話號碼"),
                ),
                (
                    "ADDRESS",
                    models.CharField(default="", max_length=25, verbose_name="使用者地址"),
                ),
                ("GDATE", models.DateTimeField(default="", verbose_name="取件時間")),
                (
                    "S_CODE",
                    models.ImageField(default="", upload_to="", verbose_name="取件條碼"),
                ),
                (
                    "G_CODE",
                    models.ImageField(default="", upload_to="", verbose_name="送件條碼"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fmachineinfo",
            fields=[
                (
                    "FMID",
                    models.CharField(
                        default="",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="摺衣機編號",
                    ),
                ),
                (
                    "STATE",
                    models.CharField(default="", max_length=10, verbose_name="使用狀態"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="hstate",
            fields=[
                (
                    "ORDID1",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="訂單編號"
                    ),
                ),
                (
                    "MEMID1",
                    models.CharField(default="", max_length=36, verbose_name="使用者編號"),
                ),
                ("APPID1", models.IntegerField(default=5, verbose_name="app編號")),
                ("C_AMOUNT1", models.IntegerField(default=0, verbose_name="花費的碳稅")),
                ("GPOINT1", models.IntegerField(default=0, verbose_name="獲得的點數")),
                ("AMOUNT1", models.IntegerField(default=0, verbose_name="消費總金額")),
                ("CDATE1", models.DateTimeField(default="", verbose_name="成立時間")),
                (
                    "WMODE1",
                    models.CharField(default="", max_length=10, verbose_name="洗滌模式"),
                ),
                (
                    "LMODE1",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
                (
                    "FMODE1",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
                (
                    "GIVE1",
                    models.CharField(default="", max_length=15, verbose_name="送洗方式"),
                ),
                (
                    "COLLAR1",
                    models.CharField(default="", max_length=15, verbose_name="領取方式"),
                ),
                (
                    "ADDITION1",
                    models.CharField(default="無", max_length=15, verbose_name="加購商品"),
                ),
                ("HDATE1", models.IntegerField(default=0, verbose_name="處理衣物時長")),
                (
                    "SHOPID1",
                    models.CharField(default="", max_length=10, verbose_name="店鋪編號"),
                ),
                (
                    "WMID1",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "FMID1",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "LOCKID1",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                ("PFTIME1", models.DateTimeField(default="", verbose_name="預計完成的時間")),
                ("CLTIME1", models.DateTimeField(default="", verbose_name="領取時間")),
            ],
        ),
        migrations.CreateModel(
            name="lockerinfo",
            fields=[
                (
                    "LOCKID",
                    models.CharField(
                        default="",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="鎖櫃編號",
                    ),
                ),
                (
                    "STATE",
                    models.CharField(default="", max_length=10, verbose_name="使用狀態"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="member",
            fields=[
                (
                    "MEMID",
                    models.CharField(
                        default="",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                        verbose_name="使用者編號",
                    ),
                ),
                (
                    "PHONE",
                    models.CharField(default="", max_length=10, verbose_name="使用者電話號碼"),
                ),
                (
                    "ADDRESS",
                    models.CharField(default="", max_length=25, verbose_name="使用者地址"),
                ),
                (
                    "AUTHORIZATION",
                    models.BooleanField(default=False, verbose_name="授權"),
                ),
                (
                    "CARD1",
                    models.CharField(default="無", max_length=16, verbose_name="信用卡卡號1"),
                ),
                (
                    "CARD2",
                    models.CharField(default="無", max_length=16, verbose_name="信用卡卡號2"),
                ),
                (
                    "CARD3",
                    models.CharField(default="無", max_length=16, verbose_name="信用卡卡號3"),
                ),
                (
                    "CARD4",
                    models.CharField(default="無", max_length=16, verbose_name="信用卡卡號4"),
                ),
                (
                    "CARD5",
                    models.CharField(default="無", max_length=16, verbose_name="信用卡卡號5"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mode",
            fields=[
                (
                    "MODE",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="模式名稱",
                    ),
                ),
                ("TIME", models.IntegerField(default=0, verbose_name="所需時間")),
                ("MONEY", models.IntegerField(default=0, verbose_name="價格")),
                ("TAX", models.IntegerField(default=0, verbose_name="碳稅")),
                ("POINTS", models.IntegerField(default=0, verbose_name="碳點數")),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "ORDID",
                    models.CharField(
                        default="",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="訂單編號",
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=36, verbose_name="使用者編號"),
                ),
                ("APPID", models.IntegerField(default=5, verbose_name="app編號")),
                ("C_AMOUNT", models.IntegerField(default=0, verbose_name="花費的碳稅")),
                ("GPOINT", models.IntegerField(default=0, verbose_name="獲得的點數")),
                ("AMOUNT", models.IntegerField(default=0, verbose_name="消費總金額")),
                ("CDATE", models.DateTimeField(default="", verbose_name="成立時間")),
                (
                    "WMODE",
                    models.CharField(default="", max_length=10, verbose_name="洗滌模式"),
                ),
                (
                    "LMODE",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
                (
                    "FMODE",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
                (
                    "GIVE",
                    models.CharField(default="", max_length=15, verbose_name="送洗方式"),
                ),
                (
                    "COLLAR",
                    models.CharField(default="", max_length=15, verbose_name="領取方式"),
                ),
                (
                    "ADDITION",
                    models.CharField(default="無", max_length=15, verbose_name="加購商品"),
                ),
                ("HDATE", models.IntegerField(default=0, verbose_name="處理衣物時長")),
                (
                    "SHOPID",
                    models.CharField(default="", max_length=10, verbose_name="店鋪編號"),
                ),
                (
                    "WMID",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "FMID",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "LOCKID",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                ("CLTIME", models.DateTimeField(default="", verbose_name="領取時間")),
            ],
        ),
        migrations.CreateModel(
            name="store",
            fields=[
                (
                    "SHOPID",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="店鋪編號",
                    ),
                ),
                (
                    "ADDRESS",
                    models.CharField(default="", max_length=25, verbose_name="店家地址"),
                ),
                ("WMAMOUNT", models.IntegerField(default=0, verbose_name="洗烘衣機數量")),
                ("FMAMOUNT", models.IntegerField(default=0, verbose_name="摺衣機數量")),
            ],
        ),
        migrations.CreateModel(
            name="wmachineinfo",
            fields=[
                (
                    "WMID",
                    models.CharField(
                        default="",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="洗烘衣機編號",
                    ),
                ),
                (
                    "STATE",
                    models.CharField(default="", max_length=10, verbose_name="使用狀態"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="wlmachin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "WMID",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                ("TIME", models.IntegerField(default=0, verbose_name="所需時間")),
                (
                    "WMODE",
                    models.CharField(default="", max_length=10, verbose_name="洗衣模式"),
                ),
                (
                    "LMODE",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
            ],
            options={"unique_together": {("WMID", "ORDID")},},
        ),
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=10, verbose_name="使用者編號"),
                ),
                ("RDATE", models.DateTimeField(default="", verbose_name="回報時間")),
                (
                    "DISC",
                    models.CharField(default="", max_length=500, verbose_name="問題描述"),
                ),
            ],
            options={"unique_together": {("MEMID", "RDATE")},},
        ),
        migrations.CreateModel(
            name="lock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "LOCKID",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                ("INDATE", models.DateTimeField(default="", verbose_name="進入時間")),
                ("OUTDATE", models.DateTimeField(default="", verbose_name="出來時間")),
            ],
            options={"unique_together": {("LOCKID", "ORDID")},},
        ),
        migrations.CreateModel(
            name="flmachin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FMID",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                ("TIME", models.IntegerField(default=0, verbose_name="所需時間")),
                (
                    "FMODE",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
            ],
            options={"unique_together": {("FMID", "ORDID")},},
        ),
    ]
