# Generated by Django 4.1.5 on 2023-01-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_hstate"),
    ]

    operations = [
        migrations.DeleteModel(name="hstate",),
    ]
