# Generated by Django 4.1.5 on 2023-01-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_hstate"),
    ]

    operations = [
        migrations.DeleteModel(name="hstate",),
    ]
