# Generated by Django 4.1.5 on 2023-01-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_hstate_order"),
    ]

    operations = [
        migrations.DeleteModel(name="lock",),
    ]
