# Generated by Django 4.1.5 on 2023-01-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_lock"),
    ]

    operations = [
        migrations.DeleteModel(name="flmachin",),
        migrations.DeleteModel(name="lock",),
        migrations.DeleteModel(name="report",),
        migrations.DeleteModel(name="wlmachin",),
    ]
