# Generated by Django 4.1.5 on 2023-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_delete_flmachin_delete_lock_delete_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="flmachin",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "FMID",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                ("TIME", models.IntegerField(default=0, verbose_name="所需時間")),
                (
                    "FMODE",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="lock",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "LOCKID",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                (
                    "INDATE",
                    models.CharField(default="", max_length=50, verbose_name="進入時間"),
                ),
                (
                    "OUTDATE",
                    models.CharField(default="", max_length=50, verbose_name="出來時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=10, verbose_name="使用者編號"),
                ),
                ("RDATE", models.DateTimeField(default="", verbose_name="回報時間")),
                (
                    "DISC",
                    models.CharField(default="", max_length=500, verbose_name="問題描述"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="wlmachin",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "WMID",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "ORDID",
                    models.CharField(default="", max_length=10, verbose_name="訂單編號"),
                ),
                ("TIME", models.IntegerField(default=0, verbose_name="所需時間")),
                (
                    "WMODE",
                    models.CharField(default="", max_length=10, verbose_name="洗衣模式"),
                ),
                (
                    "LMODE",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
            ],
        ),
    ]
