# Generated by Django 4.1.5 on 2023-01-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_notice"),
    ]

    operations = [
        migrations.DeleteModel(name="notice",),
    ]
