# Generated by Django 4.1.5 on 2023-01-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_notice"),
    ]

    operations = [
        migrations.DeleteModel(name="hstate",),
        migrations.DeleteModel(name="order",),
    ]
