# Generated by Django 4.1.5 on 2023-01-10 03:56

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_hstate_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="LOGIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FKcheck",
                    models.CharField(default=myapp.models.UUIDrand, max_length=36),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("Raccesscode", models.CharField(max_length=43)),
            ],
        ),
    ]
