# Generated by Django 4.1.5 on 2023-01-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_login"),
    ]

    operations = [
        migrations.DeleteModel(name="member",),
    ]
