# Generated by Django 4.1.5 on 2023-01-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_member"),
    ]

    operations = [
        migrations.DeleteModel(name="member",),
    ]
