# Generated by Django 4.1.5 on 2023-01-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_member"),
    ]

    operations = [
        migrations.DeleteModel(name="member",),
    ]
