# Generated by Django 4.1.5 on 2023-01-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0033_member"),
    ]

    operations = [
        migrations.DeleteModel(name="hstate",),
        migrations.DeleteModel(name="notice",),
        migrations.DeleteModel(name="order",),
        migrations.DeleteModel(name="report",),
    ]
