# Generated by Django 4.1.5 on 2023-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_delete_hstate_delete_notice_delete_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="hstate",
            fields=[
                (
                    "ORDID1",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="訂單編號"
                    ),
                ),
                (
                    "MEMID1",
                    models.CharField(default="", max_length=43, verbose_name="使用者編號"),
                ),
                ("APPID1", models.IntegerField(default=5, verbose_name="app編號")),
                ("C_AMOUNT1", models.IntegerField(default=0, verbose_name="花費的碳稅")),
                ("GPOINT1", models.IntegerField(default=0, verbose_name="獲得的點數")),
                ("AMOUNT1", models.IntegerField(default=0, verbose_name="消費總金額")),
                ("CDATE1", models.DateTimeField(default="", verbose_name="成立時間")),
                (
                    "WMODE1",
                    models.CharField(default="", max_length=10, verbose_name="洗滌模式"),
                ),
                (
                    "LMODE1",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
                (
                    "FMODE1",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
                (
                    "GIVE1",
                    models.CharField(default="", max_length=15, verbose_name="送洗方式"),
                ),
                (
                    "COLLAR1",
                    models.CharField(default="", max_length=15, verbose_name="領取方式"),
                ),
                (
                    "ADDITION1",
                    models.CharField(default="無", max_length=100, verbose_name="加購商品"),
                ),
                ("HDATE1", models.IntegerField(default=0, verbose_name="處理衣物時長")),
                (
                    "SHOPID1",
                    models.CharField(default="", max_length=10, verbose_name="店鋪編號"),
                ),
                (
                    "WMID1",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "FMID1",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "LOCKID1",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                (
                    "BAGID1",
                    models.CharField(default="", max_length=10, verbose_name="洗衣袋編號"),
                ),
                ("PFTIME1", models.DateTimeField(default="", verbose_name="預計完成的時間")),
                ("CLTIME1", models.DateTimeField(default="", verbose_name="領取時間")),
                (
                    "CLOTH1",
                    models.CharField(default="", max_length=15, verbose_name="衣服處理"),
                ),
                (
                    "COLSTATE1",
                    models.CharField(default="", max_length=15, verbose_name="領取狀態"),
                ),
                (
                    "PAYSTATE1",
                    models.CharField(default="", max_length=15, verbose_name="付款狀態"),
                ),
                (
                    "JS1",
                    models.CharField(default="", max_length=15, verbose_name="js1"),
                ),
                (
                    "JS2",
                    models.CharField(default="", max_length=15, verbose_name="js2"),
                ),
                (
                    "JS3",
                    models.CharField(default="", max_length=15, verbose_name="js3"),
                ),
                (
                    "JS4",
                    models.CharField(default="", max_length=15, verbose_name="js4"),
                ),
                (
                    "JS5",
                    models.CharField(default="", max_length=15, verbose_name="js5"),
                ),
                (
                    "JS6",
                    models.CharField(default="", max_length=15, verbose_name="js6"),
                ),
                (
                    "JS7",
                    models.CharField(default="", max_length=15, verbose_name="js7"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notice",
            fields=[
                (
                    "NID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="通知編號"
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=43, verbose_name="使用者編號"),
                ),
                (
                    "NCONTENT",
                    models.CharField(default="", max_length=100, verbose_name="通知內容"),
                ),
                (
                    "NLINK",
                    models.CharField(default="", max_length=100, verbose_name="通知連接"),
                ),
                ("NTIME", models.DateTimeField(default="", verbose_name="通知時間")),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "ORDID",
                    models.CharField(
                        default="",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="訂單編號",
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=43, verbose_name="使用者編號"),
                ),
                ("APPID", models.IntegerField(default=5, verbose_name="app編號")),
                ("C_AMOUNT", models.IntegerField(default=0, verbose_name="花費的碳稅")),
                ("GPOINT", models.IntegerField(default=0, verbose_name="獲得的點數")),
                ("AMOUNT", models.IntegerField(default=0, verbose_name="消費總金額")),
                ("CDATE", models.DateTimeField(default="", verbose_name="成立時間")),
                (
                    "WMODE",
                    models.CharField(default="", max_length=10, verbose_name="洗滌模式"),
                ),
                (
                    "LMODE",
                    models.CharField(default="", max_length=10, verbose_name="乾燥模式"),
                ),
                (
                    "FMODE",
                    models.CharField(default="", max_length=10, verbose_name="摺衣模式"),
                ),
                (
                    "GIVE",
                    models.CharField(default="", max_length=15, verbose_name="送洗方式"),
                ),
                (
                    "COLLAR",
                    models.CharField(default="", max_length=15, verbose_name="領取方式"),
                ),
                (
                    "ADDITION",
                    models.CharField(default="無", max_length=100, verbose_name="加購商品"),
                ),
                ("HDATE", models.IntegerField(default=0, verbose_name="處理衣物時長")),
                (
                    "SHOPID",
                    models.CharField(default="", max_length=10, verbose_name="店鋪編號"),
                ),
                (
                    "WMID",
                    models.CharField(default="", max_length=10, verbose_name="洗烘衣機編號"),
                ),
                (
                    "FMID",
                    models.CharField(default="", max_length=10, verbose_name="摺衣機編號"),
                ),
                (
                    "LOCKID",
                    models.CharField(default="", max_length=10, verbose_name="鎖櫃編號"),
                ),
                (
                    "BAGID",
                    models.CharField(default="", max_length=10, verbose_name="洗衣袋編號"),
                ),
                ("CLTIME", models.DateTimeField(default="", verbose_name="領取時間")),
            ],
        ),
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=43, verbose_name="使用者編號"),
                ),
                ("RDATE", models.DateTimeField(default="", verbose_name="回報時間")),
                (
                    "DISC",
                    models.CharField(default="", max_length=500, verbose_name="問題描述"),
                ),
            ],
        ),
    ]
