# Generated by Django 4.1.5 on 2023-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_delete_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="編號"
                    ),
                ),
                (
                    "MEMID",
                    models.CharField(default="", max_length=43, verbose_name="使用者編號"),
                ),
                ("RDATE", models.DateTimeField(default="", verbose_name="回報時間")),
                (
                    "TITLE",
                    models.CharField(default="", max_length=50, verbose_name="問題標題"),
                ),
                (
                    "DISC",
                    models.CharField(default="", max_length=500, verbose_name="問題描述"),
                ),
            ],
        ),
    ]
