# Generated by Django 4.1.5 on 2023-01-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0039_member"),
    ]

    operations = [
        migrations.DeleteModel(name="member",),
    ]
