# Generated by Django 4.1.5 on 2023-01-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0041_member"),
    ]

    operations = [
        migrations.DeleteModel(name="hstate",),
    ]
